# Generated by Django 5.1.15 on 2026-03-11 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('employment_type', models.CharField(choices=[('hourly', 'Hourly'), ('salaried', 'Salaried')], default='salaried', max_length=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in DKK (for hourly employment).', max_digits=10, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly gross salary in DKK (for salaried employment).', max_digits=12, null=True)),
                ('weekly_hours_fixed', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed weekly hours. Leave blank if using min/max range.', max_digits=5, null=True)),
                ('weekly_hours_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weekly hours (range mode).', max_digits=5, null=True)),
                ('weekly_hours_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weekly hours (range mode).', max_digits=5, null=True)),
                ('payroll_period_start_day', models.IntegerField(default=1, help_text='Day of month when payroll period starts. E.g. 20 means the 20th of previous month to the 19th of current month.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('tax_card_type', models.CharField(choices=[('hovedkort', 'Hovedkort (primary)'), ('bikort', 'Bikort (secondary)')], default='hovedkort', max_length=10)),
                ('vacation_type', models.CharField(choices=[('feriekonto', 'Paid to FerieKonto'), ('accrued', 'Accrued as leave balance')], default='feriekonto', max_length=10)),
                ('vacation_days_per_year', models.DecimalField(decimal_places=2, default=25, help_text='Total vacation days per year (Danish default: 25).', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
