# Generated by Django 6.0.2 on 2026-05-18 08:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly short name. Auto-generated from name, but editable.', max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, default='', help_text="Bootstrap Icons class, e.g. 'bi-briefcase'.", max_length=50)),
                ('custom_icon', models.FileField(blank=True, default='', help_text='Custom icon (PNG or SVG, max 512 KB).', upload_to='workplace_icons/')),
                ('color', models.CharField(blank=True, default='', help_text="Background hex colour for the avatar circle, e.g. '#6366f1'.", max_length=7)),
                ('accent_color', models.CharField(blank=True, default='', help_text='Accent hex colour for icon tint and page theming.', max_length=7)),
                ('employment_type', models.CharField(choices=[('hourly', 'Hourly'), ('salaried', 'Salaried')], default='salaried', max_length=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in DKK (for hourly employment).', max_digits=10, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly gross salary in DKK (for salaried employment).', max_digits=12, null=True)),
                ('weekly_hours_fixed', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed weekly hours. Leave blank if using min/max range.', max_digits=5, null=True)),
                ('weekly_hours_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weekly hours (range mode).', max_digits=5, null=True)),
                ('weekly_hours_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weekly hours (range mode).', max_digits=5, null=True)),
                ('payroll_period_start_day', models.IntegerField(default=1, help_text='Day of month when payroll period starts. E.g. 20 means the 20th of previous month to the 19th of current month.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('tax_card_type', models.CharField(choices=[('hovedkort', 'Hovedkort (primary)'), ('bikort', 'Bikort (secondary)')], default='hovedkort', max_length=10)),
                ('tax_pull_day', models.IntegerField(default=18, help_text='Day of the month when the employer pulls your tax card from SKAT. Tax profile changes after this day take effect next month. Typically between the 15th and 20th.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('vacation_type', models.CharField(choices=[('feriekonto', 'Paid to FerieKonto'), ('accrued', 'Accrued as leave balance')], default='feriekonto', max_length=10)),
                ('pension_employee_percent', models.DecimalField(decimal_places=2, default=0, help_text="Employee's own pension contribution (%).", max_digits=5)),
                ('pension_employer_percent', models.DecimalField(decimal_places=2, default=0, help_text="Employer's pension contribution (%).", max_digits=5)),
                ('fritvalgskonto_enabled', models.BooleanField(default=False, help_text='Enable fritvalgskonto (flexible account).')),
                ('fritvalgskonto_percent', models.DecimalField(decimal_places=2, default=0, help_text='Fritvalgskonto percentage of gross salary.', max_digits=5)),
                ('fritvalgskonto_payout_type', models.CharField(choices=[('accrues', 'Accrues (saved up)'), ('paid_monthly', 'Paid out every month')], default='accrues', help_text='Whether fritvalgskonto accrues or is paid out monthly.', max_length=15)),
                ('ferietillaeg_enabled', models.BooleanField(default=False, help_text='Enable ferietillæg (vacation supplement).')),
                ('ferietillaeg_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Ferietillæg as % of yearly gross, typically ~1%.', max_digits=5)),
                ('ferietillaeg_payout_months', models.CharField(blank=True, default='5,8', help_text="Comma-separated month numbers for payout (e.g. '5,8' for May & August).", max_length=50)),
                ('default_shift_start_time', models.TimeField(blank=True, help_text='Default start time for planned shifts.', null=True)),
                ('default_shift_end_time', models.TimeField(blank=True, help_text='Default end time for planned shifts.', null=True)),
                ('default_shift_break_minutes', models.PositiveIntegerField(default=0, help_text='Default break time in minutes for planned shifts.')),
                ('default_shift_type', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('sick_leave', 'Sick leave (with pay)'), ('paid_absence', 'Paid absence'), ('vacation', 'Vacation')], default='on_site', help_text='Default session type for planned shifts.', max_length=15)),
                ('hour_goal_type', models.CharField(blank=True, choices=[('weekly', 'Per week'), ('monthly', 'Per month')], default='', help_text='Whether the hour goal is per week or per month. Leave blank to disable.', max_length=10)),
                ('hour_goal_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum hours goal (or exact goal if max is blank).', max_digits=6, null=True)),
                ('hour_goal_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum hours goal (leave blank for a fixed target instead of range).', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
