# Generated by Django 6.0.2 on 2026-05-18 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in DKK (for hourly employment).', max_digits=10, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly gross salary in DKK (for salaried employment).', max_digits=12, null=True)),
                ('effective_from', models.DateField(help_text='This rate applies from this date forward.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_rates', to='workplaces.workplace')),
            ],
            options={
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('workplace', 'effective_from'), name='unique_rate_per_date')],
            },
        ),
    ]
