# Generated by Django 5.1.15 on 2026-03-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='vacation_days_per_year',
        ),
        migrations.AddField(
            model_name='workplace',
            name='fritvalgskonto_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fritvalgskonto percentage of gross salary.', max_digits=5),
        ),
        migrations.AddField(
            model_name='workplace',
            name='pension_employee_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Employee's own pension contribution (%).", max_digits=5),
        ),
        migrations.AddField(
            model_name='workplace',
            name='pension_employer_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Employer's pension contribution (%).", max_digits=5),
        ),
    ]
