# Generated by Django 5.1.15 on 2026-03-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0002_remove_workplace_vacation_days_per_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='fritvalgskonto_payout_type',
            field=models.CharField(choices=[('accrues', 'Accrues (saved up)'), ('paid_monthly', 'Paid out every month')], default='accrues', help_text='Whether fritvalgskonto accrues or is paid out monthly.', max_length=15),
        ),
    ]
