# Generated by Django 5.1.15 on 2026-03-11 13:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0003_workplace_fritvalgskonto_payout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='ferietillaeg_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Ferietillæg as % of yearly gross, typically ~1%. Set 0 to disable.', max_digits=5),
        ),
    ]
