# Generated by Django 5.1.15 on 2026-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0005_workplace_ferietillaeg_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='color',
            field=models.CharField(blank=True, default='', help_text="Hex colour for the workplace, e.g. '#6366f1'.", max_length=7),
        ),
        migrations.AddField(
            model_name='workplace',
            name='icon',
            field=models.CharField(blank=True, default='', help_text="Bootstrap Icons class, e.g. 'bi-briefcase'.", max_length=50),
        ),
    ]
