# Generated by Django 5.1.15 on 2026-03-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0006_workplace_color_workplace_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='custom_icon',
            field=models.FileField(blank=True, default='', help_text='Custom icon (PNG or SVG, max 512 KB).', upload_to='workplace_icons/'),
        ),
    ]
