# Generated by Django 5.1.15 on 2026-03-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0007_add_custom_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Accent hex colour for icon tint and page theming.', max_length=7),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='color',
            field=models.CharField(blank=True, default='', help_text="Background hex colour for the avatar circle, e.g. '#6366f1'.", max_length=7),
        ),
    ]
