# Generated by Django 5.1.15 on 2026-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0008_add_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='fritvalgskonto_enabled',
            field=models.BooleanField(default=False, help_text='Enable fritvalgskonto (flexible account).'),
        ),
    ]
