# Generated by Django 5.1.15 on 2026-03-11 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0009_workplace_fritvalgskonto_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='tax_pull_day',
            field=models.IntegerField(default=15, help_text='Day of the month when the employer pulls your tax card from SKAT. Tax profile changes after this day take effect next month. Typically between the 15th and 20th.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
