# Generated by Django 5.1.15 on 2026-03-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0011_alter_workplace_tax_pull_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='ferietillaeg_payout_months',
            field=models.CharField(blank=True, default='5,8', help_text="Comma-separated month numbers for payout (e.g. '5,8' for May & August).", max_length=50),
        ),
    ]
