# Generated by Django 5.1.15 on 2026-03-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0012_workplace_ferietillaeg_payout_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='default_shift_break_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Default break time in minutes for planned shifts.'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='default_shift_end_time',
            field=models.TimeField(blank=True, help_text='Default end time for planned shifts.', null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='default_shift_start_time',
            field=models.TimeField(blank=True, help_text='Default start time for planned shifts.', null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='default_shift_type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('sick_leave', 'Sick leave (with pay)'), ('paid_absence', 'Paid absence'), ('vacation', 'Vacation')], default='on_site', help_text='Default session type for planned shifts.', max_length=15),
        ),
    ]
