# Generated by Django 5.1.15 on 2026-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0013_workplace_default_shift_break_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='hour_goal_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum hours goal (leave blank for a fixed target instead of range).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='hour_goal_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum hours goal (or exact goal if max is blank).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='hour_goal_type',
            field=models.CharField(blank=True, choices=[('weekly', 'Per week'), ('monthly', 'Per month')], default='', help_text='Whether the hour goal is per week or per month. Leave blank to disable.', max_length=10),
        ),
    ]
