# Generated by Django 6.0.7 on 2026-07-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Matches a job id in scheduler.registry.', unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('interval', 'Every N seconds'), ('daily', 'Daily at a set time')], max_length=16)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, help_text="For 'Every N seconds' jobs — the gap between runs.", null=True)),
                ('daily_time', models.TimeField(blank=True, help_text="For 'Daily' jobs — the local time of day it runs.", null=True)),
                ('next_run_at', models.DateTimeField(blank=True, help_text='When the loop will next consider this job due.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('last_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
