# Generated by Django 6.0.7 on 2026-07-20 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=0, help_text='Break time in minutes (deducted from total).')),
                ('shift_type', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('sick_leave', 'Sick leave'), ('paid_absence', 'Paid absence'), ('vacation', 'Vacation')], default='on_site', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('approved', 'Approved')], default='planned', max_length=10)),
                ('arrival_confirmed', models.BooleanField(default=False, help_text='Whether the user has confirmed/updated their arrival time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_shifts', to='workplaces.workplace')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date'], name='shifts_plan_date_bd13f8_idx'), models.Index(fields=['workplace', 'date'], name='shifts_plan_workpla_f6dd82_idx'), models.Index(fields=['status'], name='shifts_plan_status_7536fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=0, help_text='Break time in minutes (deducted from total).')),
                ('shift_type', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('sick_leave', 'Sick leave'), ('paid_absence', 'Paid absence'), ('vacation', 'Vacation')], default='on_site', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms', models.ForeignKey(blank=True, help_text='Employment terms active when this shift was worked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='workplaces.contracttermset')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='workplaces.workplace')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date'], name='shifts_shif_date_716311_idx'), models.Index(fields=['workplace', 'date'], name='shifts_shif_workpla_563529_idx')],
            },
        ),
    ]
