# Generated by Django 6.0.2 on 2026-07-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedshift',
            name='shift_type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('sick_leave', 'Sick leave'), ('paid_absence', 'Paid absence'), ('vacation', 'Vacation')], default='on_site', max_length=15),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('sick_leave', 'Sick leave'), ('paid_absence', 'Paid absence'), ('vacation', 'Vacation')], default='on_site', max_length=15),
        ),
    ]
