# Generated by Django 6.0.7 on 2026-07-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedshift',
            name='invite_uid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='invite_uid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
