# Generated by Django 5.1.15 on 2026-03-11 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_deduction', models.DecimalField(decimal_places=2, help_text='Monthly personal tax deduction (personfradrag) in DKK.', max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, help_text='Combined municipality + health tax rate (trækprocent).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('church_tax_percent', models.DecimalField(decimal_places=2, default=0, help_text='Church tax rate (kirkeskat). Set to 0 if not a member.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('am_bidrag_percent', models.DecimalField(decimal_places=2, default=8.0, help_text='AM-bidrag (labour market contribution), typically 8%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('effective_from', models.DateField(help_text='This profile applies from this date forward.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.IntegerField(choices=[(0, 'Monday'), (6, 'Sunday')], default=0, help_text='0 = Monday, 6 = Sunday')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
