# Generated by Django 5.1.15 on 2026-06-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_atp_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='projection_method',
            field=models.CharField(choices=[('ema', 'Exponential moving average (recent months weighted higher)'), ('avg', 'Simple average')], default='ema', help_text='How to estimate future hours from your historical shifts.', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='projection_trailing_months',
            field=models.PositiveIntegerField(default=6, help_text='Number of past months used to compute the projection.'),
        ),
    ]
