# Generated by Django 6.0.7 on 2026-07-20 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='This ATP configuration applies from this date forward.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch. While this is off BitGigs sends no mail at all and features that need it stay hidden.')),
                ('host', models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('security', models.CharField(choices=[('starttls', 'STARTTLS (usually port 587)'), ('ssl', 'Implicit TLS / SSL (usually port 465)'), ('none', 'None — unencrypted (not recommended)')], default='starttls', max_length=10)),
                ('username', models.CharField(blank=True, help_text='Leave blank if the server accepts mail without authenticating.', max_length=255)),
                ('password_encrypted', models.CharField(blank=True, max_length=512)),
                ('from_email', models.EmailField(blank=True, help_text='The address mail is sent from. Many providers require this to match the account you authenticate as.', max_length=254)),
                ('from_name', models.CharField(blank=True, default='BitGigs', help_text='Display name shown beside the from address.', max_length=100)),
                ('timeout', models.PositiveIntegerField(default=10, help_text='Seconds to wait for the server before giving up.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('allow_password_reset', models.BooleanField(default=True, help_text="Offer 'Forgot your password?' on the login page. Needs a working mail setup; turn it off to require console recovery.")),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_deduction', models.DecimalField(decimal_places=2, help_text='Monthly personal tax deduction (personfradrag) in DKK.', max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, help_text='Combined municipality + health tax rate (trækprocent).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('church_tax_percent', models.DecimalField(decimal_places=2, default=0, help_text='Church tax rate (kirkeskat). Set to 0 if not a member.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('am_bidrag_percent', models.DecimalField(decimal_places=2, default=8.0, help_text='AM-bidrag (labour market contribution), typically 8%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('effective_from', models.DateField(help_text='This profile applies from this date forward.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (follow system)')], default='light', help_text="Color theme. Auto follows the operating system's setting.", max_length=5)),
                ('accent_color', models.CharField(default='#0e61de', help_text="The app's accent colour — buttons, links, tints and gradients all follow it.", max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a colour as #RRGGBB.')])),
                ('secondary_color', models.CharField(default='#9fd6fb', help_text='The gradient companion colour — pairs with the accent for buttons, tints and gradients.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a colour as #RRGGBB.')])),
                ('week_start', models.IntegerField(choices=[(0, 'Monday'), (6, 'Sunday')], default=0, help_text='0 = Monday, 6 = Sunday')),
                ('show_shift_type_colors', models.BooleanField(default=True, help_text='Colour calendar shift chips by type (on-site / remote / sick / …).')),
                ('show_help_button', models.BooleanField(default=True, help_text='Show the floating help button on every page. F1 and More → Help still open help when this is off.')),
                ('projection_method', models.CharField(choices=[('ema', 'Exponential moving average (recent months weighted higher)'), ('avg', 'Simple average')], default='ema', help_text='How to estimate future hours from your historical shifts.', max_length=10)),
                ('projection_trailing_months', models.PositiveIntegerField(default=6, help_text='Number of past months used to compute the projection.')),
                ('use_planned_shifts', models.BooleanField(default=True, help_text='When a future month has planned shifts, use them for its income instead of the trailing-average projection.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.CreateModel(
            name='ATPBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_min', models.DecimalField(decimal_places=2, help_text='Minimum monthly hours (inclusive).', max_digits=6)),
                ('hours_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly hours (inclusive). Leave blank for open-ended.', max_digits=6, null=True)),
                ('employee_amount', models.DecimalField(decimal_places=2, help_text='Employee ATP contribution in DKK.', max_digits=8)),
                ('employer_amount', models.DecimalField(decimal_places=2, help_text='Employer ATP contribution in DKK.', max_digits=8)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='core.atpconfiguration')),
            ],
            options={
                'ordering': ['hours_min'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_draft', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
