# Generated by Django 5.1.15 on 2026-06-06 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='This ATP configuration applies from this date forward.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_deduction', models.DecimalField(decimal_places=2, help_text='Monthly personal tax deduction (personfradrag) in DKK.', max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, help_text='Combined municipality + health tax rate (trækprocent).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('church_tax_percent', models.DecimalField(decimal_places=2, default=0, help_text='Church tax rate (kirkeskat). Set to 0 if not a member.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('am_bidrag_percent', models.DecimalField(decimal_places=2, default=8.0, help_text='AM-bidrag (labour market contribution), typically 8%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('effective_from', models.DateField(help_text='This profile applies from this date forward.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.IntegerField(choices=[(0, 'Monday'), (6, 'Sunday')], default=0, help_text='0 = Monday, 6 = Sunday')),
                ('projection_method', models.CharField(choices=[('ema', 'Exponential moving average (recent months weighted higher)'), ('avg', 'Simple average')], default='ema', help_text='How to estimate future hours from your historical shifts.', max_length=10)),
                ('projection_trailing_months', models.PositiveIntegerField(default=6, help_text='Number of past months used to compute the projection.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.CreateModel(
            name='ATPBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_min', models.DecimalField(decimal_places=2, help_text='Minimum monthly hours (inclusive).', max_digits=6)),
                ('hours_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly hours (inclusive). Leave blank for open-ended.', max_digits=6, null=True)),
                ('employee_amount', models.DecimalField(decimal_places=2, help_text='Employee ATP contribution in DKK.', max_digits=8)),
                ('employer_amount', models.DecimalField(decimal_places=2, help_text='Employer ATP contribution in DKK.', max_digits=8)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='core.atpconfiguration')),
            ],
            options={
                'ordering': ['hours_min'],
            },
        ),
    ]
