# Generated by Django 6.0.7 on 2026-07-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to', models.CharField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('test', 'Test message'), ('sent', 'Sent')], default='sent', max_length=10)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
