# Generated by Django 5.1.15 on 2026-03-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='This ATP configuration applies from this date forward.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ATPBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_min', models.DecimalField(decimal_places=2, help_text='Minimum monthly hours (inclusive).', max_digits=6)),
                ('hours_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly hours (inclusive). Leave blank for open-ended.', max_digits=6, null=True)),
                ('employee_amount', models.DecimalField(decimal_places=2, help_text='Employee ATP contribution in DKK.', max_digits=8)),
                ('employer_amount', models.DecimalField(decimal_places=2, help_text='Employer ATP contribution in DKK.', max_digits=8)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='core.atpconfiguration')),
            ],
            options={
                'ordering': ['hours_min'],
            },
        ),
    ]
