# Generated by Django 6.0.2 on 2026-07-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_onboardingdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_shift_type_colors',
            field=models.BooleanField(default=False, help_text='Colour calendar shift chips by type (on-site / remote / sick / …).'),
        ),
    ]
