# Generated by Django 6.0.7 on 2026-07-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='mask_money',
            field=models.BooleanField(default=False, help_text='Hide every money amount across the app (dashboard, analytics, payslips, …) so you can demo or screenshot without exposing pay. Hours and dates stay visible.'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='money_mask_style',
            field=models.CharField(choices=[('blur', 'Blur'), ('dots', 'Dots (••••)'), ('block', 'Blocks (▪▪▪▪)')], default='blur', help_text='How masked amounts are obscured while masking is on.', max_length=5),
        ),
    ]
