# Generated by Django 6.0.7 on 2026-07-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersettings_mask_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='money_mask_style',
            field=models.CharField(choices=[('dots', 'Dots  • • •'), ('asterisk', 'Asterisks  ⁎ ⁎ ⁎'), ('flower', 'Flowers  ⁕ ⁕ ⁕'), ('reference', 'Reference marks  ※ ※ ※'), ('hidden', 'Hidden length  • • • • •  (also hides how many digits)')], default='dots', help_text="How masked amounts are obscured. The per-glyph styles keep the length (so the magnitude is still hintable); “Hidden length” uses a fixed run so the number of digits can't be read off.", max_length=10),
        ),
    ]
