# Generated by Django 6.0.2 on 2026-07-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_default_shift_type_colors_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='use_planned_shifts',
            field=models.BooleanField(default=True, help_text='When a future month has planned shifts, use them for its income instead of the trailing-average projection.'),
        ),
    ]
