# Generated by Django 6.0.7 on 2026-07-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usersettings_money_mask_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='money_mask_style',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='mask_money',
            field=models.BooleanField(default=False, help_text='Hide every money amount across the app (dashboard, analytics, payslips, …) so you can demo or screenshot without exposing pay. Each amount becomes a fixed-length run of dots, so neither the value nor the number of digits can be read off. Hours and dates stay visible.'),
        ),
    ]
