# Generated by Django 6.0.7 on 2026-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usersettings_use_planned_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_help_button',
            field=models.BooleanField(default=True, help_text='Show the floating help button on every page. F1 and More → Help still open help when this is off.'),
        ),
    ]
