# Generated by Django 6.0.7 on 2026-07-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersettings_show_help_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (follow system)')], default='light', help_text="Color theme. Auto follows the operating system's setting.", max_length=5),
        ),
    ]
