# Generated by Django 6.0.7 on 2026-07-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mailconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='feature_analytics',
            field=models.BooleanField(default=True, help_text='Income projection and rate history.'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='feature_commuting',
            field=models.BooleanField(default=True, help_text='Commuting days for the transport deduction.'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='feature_payroll',
            field=models.BooleanField(default=True, help_text='Payroll periods and the payslip editor.'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='feature_vacation',
            field=models.BooleanField(default=True, help_text='The vacation / feriepenge overview.'),
        ),
    ]
