# Generated by Django 6.0.7 on 2026-07-19 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usersettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='accent_color',
            field=models.CharField(default='#6366f1', help_text="The app's accent colour — buttons, links, tints and gradients all follow it.", max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a colour as #RRGGBB.')]),
        ),
    ]
