# Generated by Django 6.0.7 on 2026-08-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usersettings_feature_analytics_and_more'),
        # tax must own them before core lets go, or the state has no model.
        ('tax', '0001_initial'),
    ]

    # The other half of tax/0001 — see that migration's note. State only: the
    # rows stay exactly where they are, under an app that no longer claims them.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='atpbracket',
                    name='configuration',
                ),
                migrations.DeleteModel(
                    name='TaxProfile',
                ),
                migrations.DeleteModel(
                    name='ATPBracket',
                ),
                migrations.DeleteModel(
                    name='ATPConfiguration',
                ),
            ],
            database_operations=[],
        ),
    ]
