# Generated by Django 6.0.7 on 2026-07-19 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usersettings_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='secondary_color',
            field=models.CharField(default='#9fd6fb', help_text='The gradient companion colour — pairs with the accent for buttons, tints and gradients.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a colour as #RRGGBB.')]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='accent_color',
            field=models.CharField(default='#0e61de', help_text="The app's accent colour — buttons, links, tints and gradients all follow it.", max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a colour as #RRGGBB.')]),
        ),
    ]
