# Generated by Django 6.0.7 on 2026-07-19 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usersettings_secondary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch. While this is off BitGigs sends no mail at all and features that need it stay hidden.')),
                ('host', models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('security', models.CharField(choices=[('starttls', 'STARTTLS (usually port 587)'), ('ssl', 'Implicit TLS / SSL (usually port 465)'), ('none', 'None — unencrypted (not recommended)')], default='starttls', max_length=10)),
                ('username', models.CharField(blank=True, help_text='Leave blank if the server accepts mail without authenticating.', max_length=255)),
                ('password_encrypted', models.CharField(blank=True, max_length=512)),
                ('from_email', models.EmailField(blank=True, help_text='The address mail is sent from. Many providers require this to match the account you authenticate as.', max_length=254)),
                ('from_name', models.CharField(blank=True, default='BitGigs', help_text='Display name shown beside the from address.', max_length=100)),
                ('timeout', models.PositiveIntegerField(default=10, help_text='Seconds to wait for the server before giving up.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('allow_password_reset', models.BooleanField(default=True, help_text="Offer 'Forgot your password?' on the login page. Needs a working mail setup; turn it off to require console recovery.")),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
