# Generated by Django 5.1.15 on 2026-03-25 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0013_workplace_default_shift_break_minutes_and_more'),
        ('worksessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=0, help_text='Break time in minutes (deducted from total).')),
                ('session_type', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('sick_leave', 'Sick leave (with pay)'), ('paid_absence', 'Paid absence'), ('vacation', 'Vacation')], default='on_site', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('approved', 'Approved')], default='planned', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_shifts', to='workplaces.workplace')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date'], name='worksession_date_f53247_idx'), models.Index(fields=['workplace', 'date'], name='worksession_workpla_97c147_idx'), models.Index(fields=['status'], name='worksession_status_d2cdad_idx')],
            },
        ),
    ]
