# Generated by Django 5.1.15 on 2026-03-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksessions', '0002_plannedshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedshift',
            name='arrival_confirmed',
            field=models.BooleanField(default=False, help_text='Whether the user has confirmed/updated their arrival time.'),
        ),
    ]
