# Generated by Django 6.0.2 on 2026-05-18 08:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False, help_text='Lock period to prevent edits after payslip is finalized.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='workplaces.workplace')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('workplace', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='E.g. number of hours or units.', max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per unit (e.g. hourly rate).', max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Line amount in DKK. If quantity and rate are set, this may be auto-calculated.', max_digits=12)),
                ('line_type', models.CharField(choices=[('pre_tax_add', 'Pre-tax addition'), ('pre_tax_deduct', 'Pre-tax deduction'), ('post_tax_add', 'Post-tax addition'), ('post_tax_deduct', 'Post-tax deduction'), ('info', 'Informational')], default='pre_tax_add', max_length=15)),
                ('rounding_method', models.CharField(choices=[('round', 'Round (standard)'), ('floor', 'Floor (round down)'), ('ceil', 'Ceil (round up)')], default='round', help_text="How to round this line's amount.", max_length=5)),
                ('standard_line_key', models.CharField(blank=True, choices=[('gross_pay', 'Gross pay'), ('fritvalgskonto', 'Fritvalgskonto'), ('ferietillaeg', 'Ferietillæg'), ('pension_employee', 'Own pension contribution'), ('atp_employee', 'ATP (employee)'), ('am_bidrag', 'AM-bidrag'), ('fradrag_used', 'Benyttet fradrag'), ('a_skat', 'A-skat'), ('total_tax', 'Total taxation'), ('subtotal', 'Subtotal'), ('net_pay', 'Net pay')], help_text='Set for auto-calculated standard lines. NULL for custom lines.', max_length=20, null=True)),
                ('is_editable', models.BooleanField(default=True, help_text='Whether the user can edit the amount. Standard calculated lines are read-only.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('default_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('line_type', models.CharField(choices=[('pre_tax_add', 'Pre-tax addition'), ('pre_tax_deduct', 'Pre-tax deduction'), ('post_tax_add', 'Post-tax addition'), ('post_tax_deduct', 'Post-tax deduction'), ('info', 'Informational')], default='pre_tax_add', max_length=15)),
                ('rounding_method', models.CharField(choices=[('round', 'Round (standard)'), ('floor', 'Floor (round down)'), ('ceil', 'Ceil (round up)')], default='round', help_text='How to round the line amount.', max_length=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_templates', to='workplaces.workplace')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CommutingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('commuting_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commuting_records', to='workplaces.workplace')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('workplace', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='VacationBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('accrued_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('used_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carried_over_hours', models.DecimalField(decimal_places=2, default=0, help_text='Balance carried from the previous month.', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_balances', to='workplaces.workplace')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('workplace', 'year', 'month')},
            },
        ),
    ]
