# Generated by Django 5.1.15 on 2026-03-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipline',
            name='rounding_method',
            field=models.CharField(choices=[('round', 'Round (standard)'), ('floor', 'Floor (round down)'), ('ceil', 'Ceil (round up)')], default='round', help_text="How to round this line's amount.", max_length=5),
        ),
        migrations.AddField(
            model_name='paysliplinetemplate',
            name='rounding_method',
            field=models.CharField(choices=[('round', 'Round (standard)'), ('floor', 'Floor (round down)'), ('ceil', 'Ceil (round up)')], default='round', help_text='How to round the line amount.', max_length=5),
        ),
    ]
