# Generated by Django 5.1.15 on 2026-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payslipline_rounding_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipline',
            name='is_editable',
            field=models.BooleanField(default=True, help_text='Whether the user can edit the amount. Standard calculated lines are read-only.'),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='standard_line_key',
            field=models.CharField(blank=True, choices=[('gross_pay', 'Gross pay'), ('ferietillaeg', 'Ferietillæg'), ('pension_employee', 'Own pension contribution'), ('atp_employee', 'ATP (employee)'), ('am_bidrag', 'AM-bidrag'), ('fradrag_used', 'Benyttet fradrag'), ('a_skat', 'A-skat'), ('total_tax', 'Total taxation'), ('subtotal', 'Subtotal'), ('net_pay', 'Net pay')], help_text='Set for auto-calculated standard lines. NULL for custom lines.', max_length=20, null=True),
        ),
    ]
