# Generated by Django 5.1.15 on 2026-03-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payslipline_is_editable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipline',
            name='standard_line_key',
            field=models.CharField(blank=True, choices=[('gross_pay', 'Gross pay'), ('fritvalgskonto', 'Fritvalgskonto'), ('ferietillaeg', 'Ferietillæg'), ('pension_employee', 'Own pension contribution'), ('atp_employee', 'ATP (employee)'), ('am_bidrag', 'AM-bidrag'), ('fradrag_used', 'Benyttet fradrag'), ('a_skat', 'A-skat'), ('total_tax', 'Total taxation'), ('subtotal', 'Subtotal'), ('net_pay', 'Net pay')], help_text='Set for auto-calculated standard lines. NULL for custom lines.', max_length=20, null=True),
        ),
    ]
