# Generated by Django 6.0.7 on 2026-07-21 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="A name for this calendar, e.g. 'Personal' or 'Partner'.", max_length=100)),
                ('url_encrypted', models.CharField(blank=True, max_length=2048)),
                ('enabled', models.BooleanField(default=True, help_text='While off, this calendar contributes no busy blocks.')),
                ('color', models.CharField(default='#6c757d', help_text="The colour of this calendar's busy blocks on the planning grid.", max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a colour as #RRGGBB.')])),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('last_fetch_ok', models.BooleanField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
