# Generated by Django 6.0.7 on 2026-07-21 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0001_initial'),
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarInviteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch for sending calendar invites. While off, no invites are sent regardless of per-workplace settings.')),
                ('owner_address', models.EmailField(blank=True, help_text='Your own address, added to every invite so each shift also lands in your personal calendar. May differ from your login email.', max_length=254)),
                ('default_remote_address', models.CharField(blank=True, help_text='Default location for remote shifts when a workplace sets none.', max_length=255)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Invite Settings',
                'verbose_name_plural': 'Calendar Invite Settings',
            },
        ),
        migrations.CreateModel(
            name='WorkplaceCalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_invites', models.BooleanField(default=False, help_text="Send calendar invites for this workplace's shifts.")),
                ('recipients', models.TextField(blank=True, help_text='Work email(s) to invite, one per line or comma-separated.')),
                ('title_onsite', models.CharField(default='På arbejde hos {workplace}', help_text='Event title for on-site shifts. {workplace}, {date}, {start}, {end} are substituted.', max_length=200)),
                ('title_remote', models.CharField(default='Arbejder hjemme, {workplace}', help_text='Event title for remote shifts. Same placeholders as on-site.', max_length=200)),
                ('address_onsite', models.CharField(blank=True, help_text='Location for on-site shifts. Defaults to the workplace name.', max_length=255)),
                ('address_remote', models.CharField(blank=True, help_text='Location for remote shifts. Falls back to the global default remote address.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workplace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_config', to='workplaces.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uid', models.CharField(blank=True, max_length=255)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('last_recipients', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_invites', to='workplaces.workplace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invite_uid'], name='calendar_sy_invite__556725_idx')],
            },
        ),
    ]
