# Generated by Django 6.0.7 on 2026-07-24 22:19

import django.db.models.deletion
from django.db import migrations, models

TITLE_ONSITE_DEFAULT = "På arbejde hos {workplace}"
TITLE_REMOTE_DEFAULT = "Arbejder hjemme, {workplace}"


def _first_recipient(text):
    """First address from the old free-text recipients field (comma/semicolon/
    newline separated)."""
    if not text:
        return ""
    for sep in (";", ","):
        text = text.replace(sep, "\n")
    for part in text.splitlines():
        addr = part.strip()
        if addr:
            return addr
    return ""


def copy_workplace_configs_to_contracts(apps, schema_editor):
    """Fan the old per-workplace invite config out onto each of that workplace's
    contracts. The feature is new, so this is typically a no-op — but it must run
    before the old model is dropped, and it preserves any real config. Override
    flags are set only where the old value actually differed from a default."""
    OldCfg = apps.get_model("calendar_sync", "WorkplaceCalendarConfig")
    NewCfg = apps.get_model("calendar_sync", "ContractCalendarConfig")
    Contract = apps.get_model("workplaces", "WorkplaceContract")

    for old in OldCfg.objects.all():
        recipient = _first_recipient(old.recipients)
        custom_onsite = old.title_onsite and old.title_onsite != TITLE_ONSITE_DEFAULT
        custom_remote = old.title_remote and old.title_remote != TITLE_REMOTE_DEFAULT
        for contract in Contract.objects.filter(workplace_id=old.workplace_id):
            NewCfg.objects.get_or_create(
                contract_id=contract.id,
                defaults={
                    "send_invites": old.send_invites,
                    "recipient": recipient,
                    "override_title_onsite": bool(custom_onsite),
                    "title_onsite": old.title_onsite if custom_onsite else "",
                    "override_title_remote": bool(custom_remote),
                    "title_remote": old.title_remote if custom_remote else "",
                    "override_address_remote": bool(old.address_remote),
                    "address_remote": old.address_remote,
                    "address_onsite": old.address_onsite,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0002_calendarinvitesettings_workplacecalendarconfig_and_more'),
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarinvitesettings',
            name='default_title_onsite',
            field=models.CharField(default='På arbejde hos {workplace}', help_text='Default event title for on-site shifts. {workplace}, {date}, {start}, {end} are substituted.', max_length=200),
        ),
        migrations.AddField(
            model_name='calendarinvitesettings',
            name='default_title_remote',
            field=models.CharField(default='Arbejder hjemme, {workplace}', help_text='Default event title for remote shifts. Same placeholders as on-site.', max_length=200),
        ),
        migrations.AddField(
            model_name='calendarinvitesettings',
            name='send_to_personal',
            field=models.BooleanField(default=True, help_text='Also add your own address to every invite, so each shift lands in your personal calendar too.'),
        ),
        migrations.AlterField(
            model_name='calendarinvitesettings',
            name='default_remote_address',
            field=models.CharField(blank=True, help_text='Default location for remote shifts when a contract sets none.', max_length=255),
        ),
        migrations.AlterField(
            model_name='calendarinvitesettings',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Master switch for sending calendar invites. While off, no invites are sent regardless of per-contract settings.'),
        ),
        migrations.AlterField(
            model_name='calendarinvitesettings',
            name='owner_address',
            field=models.EmailField(blank=True, help_text='Your own address for that personal-calendar copy. Leave blank to use your account email.', max_length=254),
        ),
        migrations.CreateModel(
            name='ContractCalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_invites', models.BooleanField(default=False, help_text="Send calendar invites for this contract's shifts.")),
                ('recipient', models.EmailField(blank=True, help_text='Work address to invite for this contract.', max_length=254)),
                ('override_title_onsite', models.BooleanField(default=False)),
                ('title_onsite', models.CharField(blank=True, max_length=200)),
                ('override_title_remote', models.BooleanField(default=False)),
                ('title_remote', models.CharField(blank=True, max_length=200)),
                ('override_address_remote', models.BooleanField(default=False)),
                ('address_remote', models.CharField(blank=True, max_length=255)),
                ('address_onsite', models.CharField(blank=True, help_text='Location for on-site shifts. Defaults to the workplace name.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_config', to='workplaces.workplacecontract')),
            ],
        ),
        migrations.RunPython(
            copy_workplace_configs_to_contracts, migrations.RunPython.noop
        ),
        migrations.DeleteModel(
            name='WorkplaceCalendarConfig',
        ),
    ]
