# Generated by Django 6.0.7 on 2026-07-27 13:45

from django.db import migrations, models


def backfill_content_keys(apps, schema_editor):
    """Give already-sent invites a fingerprint, so staleness works on day one.

    Deliberately calls the **real** ``calendar_sync.invites`` rather than the
    historical models this migration is handed: the fingerprint is built from
    ``ContractCalendarConfig.title_for``/``location_for``, and ``apps.get_model``
    strips custom methods. That is safe here because the work is a one-off
    backfill — on a fresh database the table is empty and this is a no-op, and on
    an existing one "current code" is exactly what we want it stamped with.

    Wrapped because it is housekeeping: a later refactor of ``invites`` must never
    be able to block a ``migrate``, only leave the keys blank (which reads as
    "unknown", the pre-backfill behaviour).
    """
    try:
        from calendar_sync.invites import backfill_content_keys as run
    except Exception:  # pragma: no cover - defensive
        return
    try:
        run()
    except Exception:  # pragma: no cover - defensive
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0003_calendarinvitesettings_default_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftinvite',
            name='content_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(backfill_content_keys, migrations.RunPython.noop),
    ]
