# Generated by Django 6.0.7 on 2026-07-28 10:27

from django.db import migrations, models
from django.db.models import F


def backfill_delivered_at(apps, schema_editor):
    """Treat every invite already sent as delivered.

    ``delivered_at`` is what separates "the recipients hold this" from "nobody
    ever got it", and clearing a failure *deletes* an invite of the second kind.
    Left null, every pre-existing invite would qualify as never-delivered — so a
    single later failure would drop a series the recipients are actually holding.
    They were sent before this field existed and there is no record saying
    otherwise, so ``sent_at`` is the honest stand-in.
    """
    ShiftInvite = apps.get_model("calendar_sync", "ShiftInvite")
    ShiftInvite.objects.filter(sent_at__isnull=False).update(delivered_at=F("sent_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0004_shiftinvite_content_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftinvite',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftinvite',
            name='send_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shiftinvite',
            name='send_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_delivered_at, migrations.RunPython.noop),
    ]
