# Generated by Django 6.0.7 on 2026-07-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0005_shiftinvite_delivered_at_shiftinvite_send_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractcalendarconfig',
            name='send_to_work',
            field=models.BooleanField(default=True, help_text="Invite the work address below. Turn off to send this contract's shifts only to your own calendar."),
        ),
    ]
