# Generated by Django 6.0.7 on 2026-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0006_contractcalendarconfig_send_to_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarinvitesettings',
            name='ask_before_resend',
            field=models.BooleanField(default=True, help_text='When you change a shift that already has an invite out and about, offer to send the update there and then. While off, the shift is simply marked out of date and the update goes with the next Send invites — nothing is ever mailed without a press either way.'),
        ),
    ]
