# Generated by Django 6.0.7 on 2026-08-26 22:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # Phase A2 of the BitBase extraction: TaxProfile / ATPConfiguration /
    # ATPBracket were carved out of ``core`` so the platform half of the app
    # carries no country's payroll rules.
    #
    # Nothing is created here. The tables already exist under their historical
    # ``core_*`` names (declared as ``db_table`` below), so this migration only
    # tells Django's state that ``tax`` owns them now; ``core``'s matching
    # delete is state-only for the same reason. 0002 does the real rename, by
    # which point both apps agree on who owns what.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ATPConfiguration',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('effective_from', models.DateField(help_text='This ATP configuration applies from this date forward.', unique=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'core_atpconfiguration',
                        'ordering': ['-effective_from'],
                    },
                ),
                migrations.CreateModel(
                    name='TaxProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('monthly_deduction', models.DecimalField(decimal_places=2, help_text='Monthly personal tax deduction (personfradrag) in DKK.', max_digits=10)),
                        ('tax_percent', models.DecimalField(decimal_places=2, help_text='Combined municipality + health tax rate (trækprocent).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                        ('church_tax_percent', models.DecimalField(decimal_places=2, default=0, help_text='Church tax rate (kirkeskat). Set to 0 if not a member.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                        ('am_bidrag_percent', models.DecimalField(decimal_places=2, default=8.0, help_text='AM-bidrag (labour market contribution), typically 8%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                        ('effective_from', models.DateField(help_text='This profile applies from this date forward.', unique=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'core_taxprofile',
                        'ordering': ['-effective_from'],
                    },
                ),
                migrations.CreateModel(
                    name='ATPBracket',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('hours_min', models.DecimalField(decimal_places=2, help_text='Minimum monthly hours (inclusive).', max_digits=6)),
                        ('hours_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly hours (inclusive). Leave blank for open-ended.', max_digits=6, null=True)),
                        ('employee_amount', models.DecimalField(decimal_places=2, help_text='Employee ATP contribution in DKK.', max_digits=8)),
                        ('employer_amount', models.DecimalField(decimal_places=2, help_text='Employer ATP contribution in DKK.', max_digits=8)),
                        ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tax.atpconfiguration')),
                    ],
                    options={
                        'db_table': 'core_atpbracket',
                        'ordering': ['hours_min'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
