# Generated by Django 6.0.7 on 2026-08-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
        # …and only once core has given the models up in state, so the two
        # apps can never both believe they own these tables.
        ('core', '0008_move_tax_models_to_tax_app'),
    ]

    # The real move: core_taxprofile -> tax_taxprofile and friends. Safe on
    # SQLite and Postgres alike (a plain table rename, no data copied), and it
    # runs after both apps agree on ownership in 0001/core-0008.
    operations = [
        migrations.AlterModelTable(
            name='atpbracket',
            table=None,
        ),
        migrations.AlterModelTable(
            name='atpconfiguration',
            table=None,
        ),
        migrations.AlterModelTable(
            name='taxprofile',
            table=None,
        ),
    ]
