# Generated by Django 6.0.7 on 2026-07-17 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, help_text='One-line description shown in search results and the manual list.', max_length=280)),
                ('body_md', models.TextField(help_text='Article body in Markdown.')),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('audience', models.CharField(choices=[('everyone', 'Everyone'), ('staff', 'Staff only'), ('admin', 'Admins only')], default='everyone', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=100, help_text='Lower numbers sort first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HelpKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('body_md', models.TextField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='help.helparticle')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddField(
            model_name='helparticle',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='articles', to='help.helpkeyword'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='articles', to='help.helppage'),
        ),
    ]
