# Generated by Django 6.0.7 on 2026-07-18 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helparticle',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent article — sub-articles nest beneath it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='help.helparticle'),
        ),
    ]
