# Generated by Django 6.0.7 on 2026-07-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_helparticle_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='helparticle',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
