# Generated by Django 6.0.7 on 2026-07-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_helparticle_archived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helparticle',
            name='audience',
            field=models.CharField(choices=[('public', 'Public (readable without login)'), ('everyone', 'Everyone'), ('staff', 'Staff only'), ('admin', 'Admins only')], default='everyone', max_length=10),
        ),
    ]
