# Generated by Django 5.1.15 on 2026-06-06 19:55

import django.core.validators
import django.db.models.deletion
import workplaces.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly short name. Auto-generated from name, but editable.', max_length=200, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text="Bootstrap Icons class, e.g. 'bi-briefcase'.", max_length=50)),
                ('custom_icon', models.FileField(blank=True, default='', help_text='Custom icon (PNG or SVG, max 512 KB).', upload_to=workplaces.models.workplace_icon_upload_to)),
                ('color', models.CharField(blank=True, default='', help_text="Background hex colour for the avatar circle, e.g. '#6366f1'.", max_length=7)),
                ('accent_color', models.CharField(blank=True, default='', help_text='Accent hex colour for icon tint and page theming.', max_length=7)),
                ('default_shift_start_time', models.TimeField(blank=True, null=True)),
                ('default_shift_end_time', models.TimeField(blank=True, null=True)),
                ('default_shift_break_minutes', models.PositiveIntegerField(default=0)),
                ('default_shift_type', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('sick_leave', 'Sick leave (with pay)'), ('paid_absence', 'Paid absence'), ('vacation', 'Vacation')], default='on_site', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkplaceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Optional label, e.g. 'Physics Lab' or 'Adjunkt 2024'.", max_length=200)),
                ('start_date', models.DateField(help_text='Date this employment arrangement starts.')),
                ('end_date', models.DateField(blank=True, help_text='Date this arrangement ends (leave blank if still active).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='workplaces.workplace')),
            ],
            options={
                'ordering': ['workplace', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractTermSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='These terms apply from this date forward within the contract.')),
                ('employment_type', models.CharField(choices=[('hourly', 'Hourly'), ('salaried', 'Salaried')], default='salaried', max_length=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in DKK (for hourly employment).', max_digits=10, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly gross salary in DKK (for salaried employment).', max_digits=12, null=True)),
                ('weekly_hours_fixed', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed weekly hours. Leave blank if using min/max range.', max_digits=5, null=True)),
                ('weekly_hours_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weekly hours (range mode).', max_digits=5, null=True)),
                ('weekly_hours_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weekly hours (range mode).', max_digits=5, null=True)),
                ('payroll_period_start_day', models.IntegerField(default=1, help_text='Day of month when payroll period starts. E.g. 20 means the 20th of previous month to the 19th of current month.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('tax_card_type', models.CharField(choices=[('hovedkort', 'Hovedkort (primary)'), ('bikort', 'Bikort (secondary)')], default='hovedkort', max_length=10)),
                ('tax_pull_day', models.IntegerField(default=18, help_text='Day of the month when the employer pulls your tax card from SKAT. Typically between the 15th and 20th.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('vacation_type', models.CharField(choices=[('feriekonto', 'Paid to FerieKonto'), ('accrued', 'Accrued as leave balance')], default='feriekonto', max_length=10)),
                ('pension_employee_percent', models.DecimalField(decimal_places=2, default=0, help_text="Employee's own pension contribution (%).", max_digits=5)),
                ('pension_employer_percent', models.DecimalField(decimal_places=2, default=0, help_text="Employer's pension contribution (%).", max_digits=5)),
                ('fritvalgskonto_enabled', models.BooleanField(default=False)),
                ('fritvalgskonto_percent', models.DecimalField(decimal_places=2, default=0, help_text='Fritvalgskonto percentage of gross salary.', max_digits=5)),
                ('fritvalgskonto_payout_type', models.CharField(choices=[('accrues', 'Accrues (saved up)'), ('paid_monthly', 'Paid out every month')], default='accrues', max_length=15)),
                ('ferietillaeg_enabled', models.BooleanField(default=False)),
                ('ferietillaeg_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Ferietillæg as % of yearly gross, typically ~1%.', max_digits=5)),
                ('ferietillaeg_payout_months', models.CharField(blank=True, default='5,8', help_text="Comma-separated month numbers for payout (e.g. '5,8' for May & August).", max_length=50)),
                ('hour_goal_type', models.CharField(blank=True, choices=[('weekly', 'Per week'), ('monthly', 'Per month')], default='', max_length=10)),
                ('hour_goal_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hour_goal_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_sets', to='workplaces.workplacecontract')),
            ],
            options={
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'effective_from'), name='unique_termset_per_date')],
            },
        ),
    ]
