# Generated by Django 5.1.15 on 2026-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplacecontract',
            options={'ordering': ['workplace', 'id']},
        ),
        migrations.RemoveField(
            model_name='workplacecontract',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workplacecontract',
            name='start_date',
        ),
        migrations.AddField(
            model_name='contracttermset',
            name='effective_until',
            field=models.DateField(blank=True, help_text='Optional. The date these terms stop applying. On the last term set this is the date the contract itself ends — leave blank while the employment is ongoing.', null=True),
        ),
    ]
