# Generated by Django 6.0.2 on 2026-07-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0002_alter_workplacecontract_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='default_shift_type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('sick_leave', 'Sick leave'), ('paid_absence', 'Paid absence'), ('vacation', 'Vacation')], default='on_site', max_length=15),
        ),
    ]
