# Generated by Django 5.1.15 on 2026-06-02 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0004_workplacecontract_contracttermset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttermset',
            name='ferietillaeg_payout_months',
            field=models.CharField(blank=True, default='5,8', help_text="Comma-separated month numbers for payout (e.g. '5,8' for May & August).", max_length=50),
        ),
        migrations.AlterField(
            model_name='contracttermset',
            name='payroll_period_start_day',
            field=models.IntegerField(default=1, help_text='Day of month when payroll period starts. E.g. 20 means the 20th of previous month to the 19th of current month.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='contracttermset',
            name='tax_pull_day',
            field=models.IntegerField(default=18, help_text='Day of the month when the employer pulls your tax card from SKAT. Typically between the 15th and 20th.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
