# Generated by Django 5.1.15 on 2026-06-06 19:29

import workplaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0007_move_default_shift_to_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='custom_icon',
            field=models.FileField(blank=True, default='', help_text='Custom icon (PNG or SVG, max 512 KB).', upload_to=workplaces.models.workplace_icon_upload_to),
        ),
    ]
