# Generated by Django 5.1.15 on 2026-06-06 19:29
import os
import shutil

from django.conf import settings
from django.db import migrations


def move_icons(apps, schema_editor):
    """Move existing custom icons from the old MEDIA_ROOT (BASE_DIR/media) to the
    new one (settings.MEDIA_ROOT) and rename them to <slug>_icon.<ext>."""
    Workplace = apps.get_model("workplaces", "Workplace")
    old_root = settings.BASE_DIR / "media"
    for wp in Workplace.objects.exclude(custom_icon="").exclude(custom_icon__isnull=True):
        old_name = wp.custom_icon.name
        ext = os.path.splitext(old_name)[1].lower() or ".png"
        new_name = f"workplace_icons/{wp.slug}_icon{ext}"
        old_path = old_root / old_name
        new_path = settings.MEDIA_ROOT / new_name
        if old_path.exists():
            new_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(old_path), str(new_path))
        wp.custom_icon = new_name
        wp.save(update_fields=["custom_icon"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0008_alter_workplace_custom_icon'),
    ]

    operations = [
        migrations.RunPython(move_icons, noop),
    ]
